repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
      - id: trailing-whitespace
        files: ^path/to/python/module
      - id: check-added-large-files
        files: ^path/to/python/module
      - id: check-case-conflict
        files: ^path/to/python/module
      - id: check-yaml
        files: ^path/to/python/module
    - repo: https://github.com/ambv/black
      rev: 23.7.0
      hooks:
      - id: black
        types: [python]
        args: ["--line-length", "90"]
        exclude: benchmarks|devito/arch|devito/builtins|devito/checkpointing|devito/core|devito/data|devito/finite_difference|devito/ir|devito/mpi|devito/operations|devito/operator|devito/passes|devito/symbolics|devito/tools|devito/types|devito/__init__.py|devito/_version.py|devito/exceptions.py|devito/logger.py|devito/parameters.py|examples|tests|docs|scripts|versioneer.py|setup.py
    - repo: https://github.com/pycqa/flake8
      rev: 6.1.0
      hooks:
      - id: flake8
        types: [python]
        exclude: benchmarks|devito/arch|devito/builtins|devito/checkpointing|devito/core|devito/data|devito/finite_difference|devito/ir|devito/mpi|devito/operations|devito/operator|devito/passes|devito/symbolics|devito/tools|devito/types|devito/__init__.py|devito/_version.py|devito/exceptions.py|devito/logger.py|devito/parameters.py|examples|tests|docs|scripts|versioneer.py
